['91porn.com,9p234.com,91p46.com,wonderfulday25.live,91splt.app']
type='m3u8'
video=['https://.*\.m3u8']
pic.re='//video[@id="player_one_html5_api"]'
pic.value='poster'
ico='http://91porn.com/favicon.ico'
strategy='eager'
['pornhub.com']
type='m3u8'
master=true
video=['.*master.m3u8']
pic.re='//link[@rel="preload"]'
pic.value='href'
wait=15
ico='https://ei.phncdn.com/www-static/favicon.ico'
['xhamster.com,xhamster3.com']
type='m3u8'
master=true
video=['https://19-18.b.cdn13.com.*master.m3u8.*','https://video7.xhcdn.com/.*\.mp4.m3u8']
pic.re='//meta[@property="og:image"]'
pic.value='content'
ico='https://static-lvlt.xhcdn.com/xh-desktop/images/favicon/favicon.ico'
b=true
['xvideos.com']
type='m3u8'
master=true
video=['https://.*hls.m3u8']
pic.re='//meta[@property="og:image"]'
pic.value='content'
ico='https://static-cdn77.xvideos-cdn.com/v3/img/skins/default/logo/xv.white.32.png'
['xnxx.com']
type='m3u8'
master=true
video=['https://.*hls.m3u8']
pic.re='//meta[@property="og:image"]'
pic.value='content'
ico='https://www.xnxx.com/favicon-32x32.png'
['eporner.com']
type='m3u8'
master=true
click = [{type='id',value='moviexxx'}]
video=['https://.*master.m3u8']
pic.re='//video[@id="EPvideo_html5_api"]'
pic.value='poster'
ico='https://static-ca-cdn.eporner.com/favicon.png'
wait=5
['beeg.com']
type='m3u8'
video=['https://.*\.mp4.m3u8','https://.*.ahcdn.com/.*\.m3u8']
pic.re='//meta[@property="og:image"]'
pic.value='content'
ico='https://beeg.com/assets/favicon-192.png'
['85tube.com']
type='mp4'
video=['https://.*remote_control.php.*']
pic.re='//meta[@property="og:image"]'
pic.value='content'
ico='https://85tube.com/favicon.ico'
['91pornplus.com']
type='m3u8'
video=['https://.*index.m3u8']
pic.re='//img[@style="object-fit: cover;"]'
pic.value='src'
wait=10
ico='https://www.91pornplus.com/assets/favicons/tvideos.ico'
['hentaimama.io']
type='mp4'
video=['https://.*.javprovider.com/.*\.mp4.*']
pic.re='//img[@class=" ls-is-cached lazyloaded"]'
pic.value='src'
ico='https://hentaimama.io/wp-content/uploads/2022/01/favicon-2.ico'
['hentaicloud.com']
type='mp4'
video=['https://www.hentaicloud.com/media/videos/.*\.mp4']
pic.re='//meta[@property="og:image"]'
pic.value='content'
ico='https://www.hentaicloud.com/favicon.ico'
['hentai.tv']
type='mp4'
video=['https://r2.1hanime.com/.*\.mp4']
click = [{type='xpath',value='//*[@id="aawp"]/div[2]/section/p/button',ignore=true},
    {type='xpath',value='// *[ @ id = "aawp"] / div[2] / div / div[1] / div[2] / figure / div / button'},
    {type='xpath',value='/html/body/div/div[1]',iframe=true}]
pic.re='//meta[@property="og:image"]'
pic.value='content'
ico='https://hentai.tv/wp-content/uploads/2022/04/cropped-cropped-favicon1-32x32.png'
['uncensoredhentai.xxx']
type='mp4'
video=['https://r2.1hanime.com/.*\.mp4','https://cdn\d+.htstreaming.com/cdn/.*\.mp4.mp4?.*']
click = [{type='xpath',value='/html/body/div/div[1]',iframe=true}]
pic.re='//*[@id="thumbnail-post"]/img'
pic.value='src'
wait=5
ico='https://uncensoredhentai.xxx/wp-content/uploads/2022/08/cropped-android-chrome-512x512-1-180x180.png'
['animeidhentai.com']
type='mp4'
bak={type='xpath',value='/html/body/span',iframe=true}
video=['https://r2.1hanime.com/.*\.mp4']
video-bak={type='xpath',value='/html/body/span/label/ul/li/a',iframe=true}
click-bak=[{type='xpath',value='//*[@id="player"]',iframe=true}]
click = [{type='xpath',value='/html/body/div/div[1]',iframe=true}]
pic.re='//meta[@property="og:image"]'
pic.value='content'
wait=10
ico='https://animeidhentai.com/storage/2021/12/cropped-App1-32x32.png'
['hentaifreak.org']
type='mp4'
video=['https://media.hentaifreak.org/.*\.mp4']
pic.re='/html/body/div[1]/div[1]/main/article/div/div/div[4]/div/p/img'
pic.value='src'
click = [{type='class',value='vjs-big-play-button'}]
wait=10
ico='https://media.hentaifreak.org/2016/10/cropped-favicon-1-32x32.png'
['hentaiworld.tv']
type='mp4'
video=['https://www.porn-d.xyz/.*\.mp4','https://jav-trailers.com/.*\.mp4','https://hentaiworld.tv/.*\.mp4']
pic.re='//meta[@property="og:image"]'
pic.value='content'
ico='https://cdn.hentaiworld.tv/wp-content/uploads/2020/04/cropped-1586514450834-32x32.png'
['hanime1.me']
type='mp4'
video=['https://cdn5-videos.motherlessmedia.com/videos/.*\.mp4',
    'https://vdownload-47.sb-cd.com/.*.mp4?.*','https://vdownload-\d+.hembed.com/.*\.mp4.*',
'https://cdne-mobile.youjizz.com/videos/.*\.mp4.*']
pic.re='//meta[@property="og:image"]'
pic.value='content'
check=true
ico='https://cdn.jsdelivr.net/gh/jokogebai/jokogebai@v1.0.0/tab_logo.jpg'
["hanime.tv"]
type='mp4'
video=['https://file\d+.gofile.io/download/.*\.mp4','https://p30.highwinds-cdn.com/.*\.mp4\?md5=.*']
pic.re='//*[@id="app"]/div[15]/main/div/div/div/div[2]/div[1]/div/div[1]/img'
pic.value='src'
ico='https://hanime.tv/favicon.png'
["hentaihaven.xxx"]
type='mp4'
video=['https://alpha.hentai.download/alpha/.*\.mp4?token=.*']
pic.re='//meta[@property="og:image"]'
pic.value='content'
ico='https://hentaihaven.xxx/www/2019/04/cropped-hentaihavenico-32x32.png'
["miohentai.com"]
type='mp4'
click=[{'value'='//*[@id="video-player"]/button','type'='xpath'}]
video=['https://cdn.miohentai.com/index.php.*']
pic.re='//meta[@property="og:image"]'
pic.value='content'
wait=10
ico='https://miohentai.com/wp-content/uploads/2016/01/favicon-1.ico'
['twitter.com']
type='m3u8'
m4s=true
b=true
wait=10
video=['https://video.twimg.com/.*\.m3u8\?container=fmp4']
pic.re='//meta[@property="og:image"]'
pic.value='content'
ico='https://abs.twimg.com/favicons/twitter.2.ico'
['motherless.com']
type='mp4'
video=['https://cdn\d+-videos.motherlessmedia.com/videos/.*\.mp4']
pic.re='//meta[@property="og:image"]'
pic.value='content'
ico='https://motherless.com/favicon.ico'
['optimize']
url='xvideos.com,xnxx.com,pornhub.com,91porn.com,9p234.com,91p46.com,wonderfulday25.live,91splt.app'
