[left]
home="首页"
collect="收藏"
tags="标签"
history="历史"
import="导入"
netdown="网络下载"
setting="设置"
[home]
tip="快去导入或者下载你心爱的视频吧"
title="标题"
img="图片"
net="网络路径"
edit="编辑模式"
[collect]
tip="快去添加你的最爱"
title="标题："
addtime="添加时间："
views="观看次数："
[imp]
tip="将视频拖动至此，最好是MP4格式"
[tag]
title="标题"
desc="描述"
img="图片"
[history]
tip="还没有什么浏览记录"
[netdown]
urltext="输入下载链接"
title="标题"
feng="封面"
headless="无头模式。如果一些网站在无头模式下无法解析，可选择关闭并加以手动辅助。"
sync="同步chrome数据"
clear="清空输入框"
[setting]
lang="语言"
privacy="隐私保护"
datadir="数据目录"